### ISSUE TITLE
Content Conversion from Old Site to New Site

### ISSUE THREAD

**Issue by hannahbireschi** [ucdavis/JMIE-IT#28]
Move content over from old site to new site to ensure no pages are blank. This content should utilize titles and subheadings as appropriate to break up the text.
Pages that need content:

- Director's message (needs to be updated with a message from Susan before Oct.1)

- WLIC

-Fellows Program

- Student Graduate Scholars

- People pages, see separate issue for more details on how to complete this

**Comment by hannahbireschi** [comment]
Student Graduate Scholars Pages:
Add each as a new person to the site
Categorize them according to year they were awarded
Upload image of them
List their research project under the research interests entry field

**Comment by hannahbireschi** [comment]
For Grad scholar Pages include:
-name
-department( this can be found in the powerpoint) inserted into the "unit" field
-research project name inserted in the "research interests"field 
-2020 or 2019 Graduate Student Scholar inserted in the "title" field
-email (can be found in the UC Davis directory)
-photo (this may need to be taken from another UC Davis site)
-categorize them as 2020 or 2019 graduate student scholars

**Comment by ciavila** [comment]
2019 Scholars have all been uploaded to website @hannahbireschi
